apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamflix
  template:
    metadata:
      labels:
        app: streamflix
    spec:
      containers:
      - name: streamflix
        image: docker.io/shobhitnagar/myapp:IMAGE_TAG
        ports:
        - containerPort: 80
